"""Calendar events, goals and logged study time.

Everything is placed around the anchor week (Monday 14 March 2022 in the frozen demo):
Alex's recurring study sessions and weekday review block, the shared Northwind SQL workshop
(which Alex's pair-study session overlaps, to show the week view's overlap layout), a
statistics deadline, the Biology midterm, and goals whose progress comes from the quiz history
in `core.py` plus the study logs below. The logs follow the quiz days in `core.HISTORY`, so Alex
has a current streak ending today and a longer best run five weeks ago.
"""

from datetime import date, timedelta

from .. import clock
from ..models import Event, Goal, StudyLog
from ..services.events import record
from .context import SeedContext

# (workspace, owner, title, kind, course, start (days_ago, hour, minute), minutes or None for all-day,
#  recurrence, repeat-until days ahead, shared, location, notes)
EVENTS = (
    (
        "northwind",
        "alex",
        "Evening ML study",
        "study",
        "ml",
        (21, 18, 0),
        90,
        "weekly",
        42,
        False,
        "Home desk",
        "One concept per session, then a 4-question quiz.",
    ),
    (
        "northwind",
        "alex",
        "Midweek statistics practice",
        "study",
        "stats",
        (19, 18, 30),
        90,
        "weekly",
        42,
        False,
        "",
        "Work through the problem set before looking at the solutions.",
    ),
    (
        "northwind",
        "alex",
        "Flashcard review block",
        "review",
        None,
        (14, 7, 30),
        30,
        "weekdays",
        None,
        False,
        "",
        "Clear the due queue before work.",
    ),
    ("northwind", "alex", "Mock quiz: ML basics", "review", "ml", (5, 17, 0), 45, "none", None, False, "", ""),
    (
        "northwind",
        "alex",
        "Pair study with Sam",
        "study",
        "sql",
        (-2, 15, 45),
        60,
        "none",
        None,
        False,
        "Library room 2",
        "Compare notes on joins and GROUP BY.",
    ),
    ("northwind", "alex", "Read: regularisation chapter", "study", "ml", (-5, 10, 0), 90, "none", None, False, "", ""),
    (
        "northwind",
        "maya",
        "SQL workshop: window functions",
        "live",
        "sql",
        (-2, 15, 0),
        90,
        "none",
        None,
        True,
        "Zoom",
        "Bring a laptop with the Northwind sample database loaded.\nRecording shared afterwards.",
    ),
    (
        "northwind",
        "maya",
        "Statistics quiz 1 closes",
        "deadline",
        "stats",
        (10, 0, 0),
        None,
        "none",
        None,
        True,
        "",
        "",
    ),
    (
        "northwind",
        "maya",
        "Statistics quiz 2 closes",
        "deadline",
        "stats",
        (-4, 0, 0),
        None,
        "none",
        None,
        True,
        "",
        "Covers confidence intervals and hypothesis testing.",
    ),
    (
        "northwind",
        "maya",
        "Office hours",
        "live",
        None,
        (11, 16, 0),
        60,
        "weekly",
        38,
        True,
        "Room 4.12",
        "Drop in with any course question.",
    ),
    ("northwind", "jonas", "Data modelling clinic", "live", "sql", (-8, 14, 0), 60, "none", None, True, "Zoom", ""),
    ("northwind", "sam", "SQL practice", "study", "sql", (-1, 19, 0), 60, "none", None, False, "", ""),
    ("northwind", "sam", "ML quiz practice", "study", "ml", (13, 9, 0), 45, "weekly", 28, False, "", ""),
    ("northwind", "priya", "Stats revision", "study", "stats", (-3, 12, 0), 60, "none", None, False, "", ""),
    (
        "biology",
        "alex",
        "Biology midterm",
        "exam",
        "cells",
        (-9, 10, 0),
        120,
        "none",
        None,
        True,
        "Hall B",
        "Chapters 1-4. Bring a pencil and your student card.",
    ),
    ("biology", "alex", "Cell membrane drill", "review", "cells", (6, 20, 0), 30, "weekly", 9, False, "", ""),
    (
        "biology",
        "lena",
        "Genetics review session",
        "live",
        "genetics",
        (-7, 17, 0),
        90,
        "none",
        None,
        True,
        "Lab 3",
        "Past-paper questions on inheritance.",
    ),
)

